### ISSUE TITLE
support validating Qiita formats

### ISSUE THREAD

**Issue by jairideout** [qiime2/Keemei#68]
Formats described [here](https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-templates.html).

**Comment by colinbrislawn** [comment]
👍  Yes please. Qiita is pretty specific, so this would be a great.

**Comment by jairideout** [comment]
Keemei has experimental support for validating Qiita sample template files, it'd be great if you could try it out and let us know if anything isn't working for you!

**Comment by colinbrislawn** [comment]
Will do! I've got two projects (one super fresh, one legacy) that I can use for testing.

**Comment by jairideout** [comment]
Awesome, thanks!

**Comment by colinbrislawn** [comment]
As discussed [over here](https://github.com/biocore/qiita/issues/1813), the standard term should now be 'Sample Information File', instead of 'Sample Template'

This is part of a larger issue: Qiita explicitly separates 'Sample Info' and 'Prep Info' into separate files **without** redundant content. As such, Keemei should probably validate 'Sample Info' and 'Prep Info' separately. Just to drive that point home, you could have 'Sample Info' throw errors when they include things like 'LinkerPrimerSequence' which are not 'Sample Info' and should instead be part of the 'Prep Info File'. 

Let me know what you think. I understand that Qiita development is an ongoing process, so this may take time to address. Guidance from @antgonza would be helpful here.

**Comment by antgonza** [comment]
I think validating both (sample/prep information files) is important but also having a "nice" converter between QIIME/Qiita map files will be desirable. Thanks!

**Comment by colinbrislawn** [comment]
The converter would be an elegant way to help qiime people start using qiita. Simple validation would be a very good place to start. 

And I'm super interested in testing these. Keep in touch!

**Comment by jairideout** [comment]
Thanks @colinbrislawn for letting me know of the new format name ("Sample Information File"). I wasn't aware of this change and will update Keemei's docs to use the new name and format spec URL.

@antgonza, is [this page](https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-templates.html) describing template files now obsolete? The link still works so it might be nice to redirect users to the new "info files" page.

> This is part of a larger issue: Qiita explicitly separates 'Sample Info' and 'Prep Info' into separate files without redundant content. As such, Keemei should probably validate 'Sample Info' and 'Prep Info' separately. 

Yep, Keemei will validate sample and prep info files separately because they are two different file formats. Right now Keemei only supports validating sample info files but there will be an option to validate prep info files in the future.

> but also having a "nice" converter between QIIME/Qiita map files will be desirable.

Converting between file formats is outside the scope of Keemei but agree it would be nice to have an easy-to-use converter somewhere. I could see this converter living in Qiita, QIIME, or a standalone package/project.

Thanks for testing this out @colinbrislawn and for your input @antgonza! Let me know if there are other improvements I can make on Keemei's end.

**Comment by antgonza** [comment]
That link is still valid and it should always be up to date.

**Comment by jairideout** [comment]
Then what is the difference between a *sample info file* and *sample template file*?

**Comment by antgonza** [comment]
Just the name. As @colinbrislawn mentioned, discussed here: https://github.com/biocore/qiita/issues/1813

**Comment by jairideout** [comment]
Thanks, I've read through biocore/qiita#1813. Why does the *sample template* page still exist? I thought the *template* files were phased out in favor of *information* files?

**Comment by colinbrislawn** [comment]
There are 'sample info files' (biological metadata) and 'prep info files' (sequencing info). The term 'info' or 'information' replaces the old term 'template' in our public facing interfaces and documentation. 

Where is the 'sample template' page? I'll get rid of it ;-)

**Comment by jairideout** [comment]
@colinbrislawn here's the "template" page:

https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-templates.html

Maybe a redirect is more appropriate?

**Comment by colinbrislawn** [comment]
Woh, that's not listed in the menus anymore, and has indeed been fully superseded by 
https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-information-files.html 

I'll make that redirect...

**Comment by jairideout** [comment]
Okay, thanks!

**Comment by colinbrislawn** [comment]
[This PR](https://github.com/biocore/qiita/pull/1826) will should overwrite the existing page and will go live on the website over the weekend.

**Comment by jairideout** [comment]
Awesome, thanks @colinbrislawn!

**Comment by jairideout** [comment]
The next Keemei release (scheduled for sometime on or before Feb 15, 2018) has the updated Qiita file format name (*sample information file* instead of *sample template file*). Qiita file format support is also noted on the [Keemei website](https://keemei.qiime2.org/). I think this issue is safe to close.
