### ISSUE TITLE
Keemei is by an 'Unverified developer' on Google

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/Keemei#89]
I recently did a security checkup with Google, and got the following warning:
![keemei_warning](https://user-images.githubusercontent.com/10355152/35294907-91ca877e-002c-11e8-9c52-be53b4b969ea.PNG)

Can we become a verified developer so that folks don't get this warning?

P.S. Mailchip (a very big company) was also listed as an unverified developer so maybe this is fine. 🤷

**Comment by jairideout** [comment]
Thanks for reporting this @colinbrislawn! This is on our radar and will be resolved within the next couple of weeks.

**Comment by jairideout** [comment]
Keemei is now a verified add-on; the "unverified" warning should no longer appear.
